### ISSUE TITLE
Disable Autofill/Autocomplete

### ISSUE THREAD

**Issue by Surg-Dev** [PrairieLearn/PrairieLearn#3839] opened 2021-02-17 19:53 UTC
Chrome and other browsers try to autofill questions with lots of dialogue boxes with addresses/locations/other information.

Could PL implement and autocomplete disable across the entire site, as it usually will not have an use on any given assignment?

The end user only has the option to disable autocomplete across all sites at the moment.

**Comment by jonatanschroeder** [comment] 2021-02-21 02:05
PrairieLearn currently disables autocomplete, but the problem is that browsers like Chrome do not always respect this setting, see: https://bugs.chromium.org/p/chromium/issues/detail?id=914451.

**Comment by eliotwrobson** [comment] 2023-01-03 22:49
Should close this issue, duplicate of https://github.com/PrairieLearn/PrairieLearn/issues/2344

**Comment by nwalters512** [comment] 2023-01-03 23:01
Thanks @eliotwrobson! @Surg-Dev, please subscribe to updates on #2344 if you'd like to follow along with any future progress.

**Closed by nwalters512** 2023-01-03 23:01 UTC
