### ISSUE TITLE
Add refresh question variant button

### ISSUE THREAD

**Issue by tbretl** [PrairieLearn/PrairieLearn#756] opened 2017-08-31 17:34 UTC
Need a button that makes it so if students log out and log back in again, they will get a new variant of any given question. This is important so that if an instructor changes the question, students don't continue working on variants of the original version.

**Comment by trombonekenny** [comment] 2019-11-07 18:40
Dupe of #233 ?

**Comment by mwest1066** [comment] 2019-11-07 19:24
Closing in favor of #1041

**Closed by mwest1066** 2019-11-07 19:24 UTC
Labels: enhancement
