### ISSUE TITLE
ansiOutput question is no longer working

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#6116] opened 2022-08-05 21:49 UTC
This question is no longer working for some reason: https://github.com/PrairieLearn/PrairieLearn/tree/master/exampleCourse/questions/demo/autograder/ansiOutput

**Comment by echuber2** [comment] 2022-08-06 00:42
Can you clarify? It works for me here:

https://www.prairielearn.org/pl/course/108/question/4111566/preview/

**Comment by jonatanschroeder** [comment] 2022-08-07 00:49
Interesting, it works on the production servers, but not when I'm running it locally...

**Comment by nwalters512** [comment] 2022-08-07 00:50
We haven't deployed to prod in a while now, so it's possible that a change landed recently that broke it 👀

**Comment by jonatanschroeder** [comment] 2022-08-07 00:54
Indeed,  I just checked out the version last announced as deployed and it works there, but not on master.

**Comment by jonatanschroeder** [comment] 2022-08-07 00:56
Submission 2 is in 8985f0c, Submission 3 is in master.

**Comment by echuber2** [comment] 2022-08-07 01:28
I'm trying a git bisect on this.

**Comment by echuber2** [comment] 2022-08-07 02:00
Here's the commit where things went wrong. I haven't been able to figure out exactly why yet:

```
89144b9d5a87b6d23b1ac95407e65aea0e89e2b1 is the first bad commit
commit 89144b9d5a87b6d23b1ac95407e65aea0e89e2b1
Author: Nathan Walters <nathan@prairielearn.com>
Date:   Tue Jul 12 16:21:15 2022 -0700

    Convert freeform question code to async/await (#5887)
```

**Comment by echuber2** [comment] 2022-08-07 02:05
@nwalters512 Could this be related to the fact that the question is a "fake" externally-graded question?

**Comment by echuber2** [comment] 2022-08-07 02:27
I believe so, because if I go to `demo/autograder/codeEditor` instead and have my solution print some ansi-colored text, it does show up as expected in the Output panel for the submission. It seems the issue is that this "fake" externally-graded question isn't showing anything for the submission at all.

**Comment by echuber2** [comment] 2022-08-07 08:03
It was just a little typo in freeform.js

**Closed** 2022-08-07 19:56 UTC
