### ISSUE TITLE
Button is visible to close PL issue without permissions

### ISSUE THREAD

**Issue by andrejgou** [PrairieLearn/PrairieLearn#1310] opened 2018-10-05 17:45 UTC
As a TA for a course I don't have permission to close issues (but professors do), yet the button is still visible.
![screenshot 2018-10-05 12 09 38](https://user-images.githubusercontent.com/14020413/46549643-57e4d980-c898-11e8-8f24-6719cc78d7a7.png)

When I click on it, I get this error message instead of something telling me about permissions
![screenshot 2018-10-05 12 09 52](https://user-images.githubusercontent.com/14020413/46549642-57e4d980-c898-11e8-882c-fe0e013582d5.png)

**Comment by tbretl** [comment] 2018-10-05 17:55
Here is the problem line, which does not allow TAs to close issues, even though TAs can see issues:
https://github.com/PrairieLearn/PrairieLearn/blob/1e69c976cb73c275d09e1a9513e1943df917e3cd/pages/instructorIssues/instructorIssues.js#L146

Either:
* Don't allow TAs to see issues, or...
* Remove button that allows TAs to close issues.

In any case:
* Generate a proper error message that says the problem is with permissions.

**Comment by mwest1066** [comment] 2018-10-05 21:01
We should wrap all "editing" instructor UI in EJS files in `if` statements like this:
```
<% if (authz_data.has_instructor_edit) { %>
<button>Delete all the important data</button>
<% } %>
```

We do this already in some places (e.g. https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs#L183) but we aren't consistent about it.

**Comment by trombonekenny** [comment] 2018-10-05 21:20
What's wrong with TAs viewing and potentially resolving issues?

**Comment by mwest1066** [comment] 2018-10-27 21:50
Similar to #758

**Comment by mwest1066** [comment] 2018-10-27 21:52
Similar to #758

**Closed** 2021-08-20 10:31 UTC
Labels: bug
