### ISSUE TITLE
Adding preview for pdf files 

### ISSUE THREAD

**Issue by AwsManas** [PrairieLearn/PrairieLearn#8687] opened 2023-10-22 23:50 UTC
When a file upload is done, preview of pdf files should be provided. 

![Screen Shot 2023-10-22 at 16 23 37](https://github.com/PrairieLearn/PrairieLearn/assets/39924378/be53e0d5-41e4-4450-83fe-aa6e3a3cb613)

**Comment by nwalters512** [comment] 2023-10-22 23:52
Duplicate of #4351 - let's move any further discussion there!

**Closed by nwalters512** 2023-10-22 23:52 UTC
