### ISSUE TITLE
Some exampleCourse questions missing client.js, server.js

### ISSUE THREAD

**Issue by tnip** [PrairieLearn/PrairieLearn#109] opened 2015-09-01 21:37 UTC
And related: the templates (located here: https://github.com/PrairieLearn/PrairieLearn/tree/master/backend/questionDefaults) seem to be missing one for Calculation types, and should really be moved to something like /templates/questions so users don't have to dig around for 'em.

**Comment by mwest1066** [comment] 2015-09-02 12:52
`client.js` and `server.js` are only required for some question types. See the list of required files here: https://github.com/PrairieLearn/PrairieLearn/blob/master/doc/writingQuestions.md

There is no default for Calculation questions, which is why Calculation questions are listed as requiring these files. I'm going to leave them under `backend/` to preserve the logical structure.

I'm not sure why users would normally need to access these? At least any more than other parts of the code.

**Comment by tnip** [comment] 2015-09-02 18:10
So there's actually a related issue - when you have new questions exist, it's assumed that client.js exists to at least populate the question into Mongo. I'm assuming that a similar situation will arise for server.js, haven't vetted that out yet.

Repro:

(1) Create a new question that's not being cached in Mongo, go through normal process of getting it into a homework
(2) Restart PrairieLearn
(3) Go into corresponding homework
(4) Try to view corresponding question

And by users, I meant developers -- just because the templates weren't in an all too obvious location. :-)

**Comment by mwest1066** [comment] 2015-09-03 04:45
I'm not understanding what the problem is here. As far as I can see, it's fine to have questions without client.js, so long as they are one of the types that doesn't need it (like MultipleChoice). If you have a Calculation question then it has to have a client.js

Are you saying that even MultipleChoice questions need a client.js? I just deleted my entire DB and restarted nodejs with the default exampleCourse, and it loaded fine (the fossilFuels question in there does not have a client.js).

**Comment by mwest1066** [comment] 2015-10-23 13:05
Closing as NOTABUG

**Closed by mwest1066** 2015-10-23 13:05 UTC
Labels: needs info
