### ISSUE TITLE
M1 chip warning

### ISSUE THREAD

**Issue by a2975667** [PrairieLearn/PrairieLearn#5414] opened 2022-02-19 00:23 UTC
Trying to start pl on a Macbook with Apple silicon. Not sure if this warning is a root cause of some auto-grading failure. 

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by a2975667** [comment] 2022-02-19 00:55
I have to be honest I am not sure. I do know we will also spin up a MySQL image together with the docker. Is there a way to reach out for details or potentially debug the issue? (I am on campus if that helps!)

**Comment by nwalters512** [comment] 2022-02-19 01:18
If you're facing an issue in production, you can reach out on Slack or open a new issue describing the problem you're facing, steps to reproduce, what you've tried so far, what happens when you run locally, etc. I'll close this issue since the warning you posted shouldn't actually impact anything.

**Closed by nwalters512** 2022-02-19 01:18 UTC

**Comment by firasm** [comment] 2022-02-24 17:09
FYI that's a warning that'll happen when you're launching Docker locally on an M1, to fix it, you just need to just add a `--platform linux/x86_64` in your `docker run` command. So it'll run like:

```
 docker run --platform linux/x86_64 ....
```
