### ISSUE TITLE
Add IPs to `submissions` table and return it PL API

### ISSUE THREAD

**Issue by andrewstec** [PrairieLearn/PrairieLearn#3256] opened 2020-10-02 16:05 UTC
As a faculty member, I would like the ability to retrieve the IP address used to submit submissions, so that I can verify the IP address is consistent with a workstation to prevent cheating.

**Comment by nwalters512** [comment] 2023-07-07 17:35
Closing as a duplicate of #6532.

**Closed by nwalters512** 2023-07-07 17:35 UTC
Labels: diff:easy
