### ISSUE TITLE
Manual Grading: add option to hide unchecked rubric items from students

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#8453] opened 2023-09-07 00:47 UTC
(Apologies if this feature already exists, I couldn't easily find it).

I typically have dozens of rubric/feedback items in my assessments (back when I used other, non PL tools) to give students super-specific feedback at scale. 

It would be really nice to have an option that "hides" feedback that isn't applied to the submission. For instance, in the example image below, I'd like the second rubric item not to show up since it doesn't apply to students.

From experience, having all the feedback items show up to the students is more trouble than it's worth and causes lots of confusion.

<img width="1166" alt="Screenshot 2023-09-06 at 5 43 40 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/cdccc30c-bea1-4732-8d19-dc256c166298">

**Comment by jonatanschroeder** [comment] 2023-09-07 01:20
Duplicate of #6777.

**Closed** 2023-09-07 21:00 UTC
