### ISSUE TITLE
Add IP information to access log

### ISSUE THREAD

**Issue by eecarrier** [PrairieLearn/PrairieLearn#2414] opened 2020-04-21 13:27 UTC
Right now there's no way for a someone to see IP address access information from the PL frontend.  It'd be helpful if the log for an assessment also included IP address information (to help with things like academic integrity investigations).

**Comment by mwest1066** [comment] 2020-04-21 13:32
To do this, we should add IP information to the `page_view_logs` table and the `middlewares/pageViewLogs.js` function. See `middlewares/logRequest.js` for how to get the IP. The IP data could then be included in the query for `pages/instructorAssessmentInstance` to both display in the log table and include in the CSV.

**Comment by nwalters512** [comment] 2023-07-07 18:11
Closing as a duplicate of #6532.

**Closed by nwalters512** 2023-07-07 18:11 UTC
Labels: diff:medium
