### ISSUE TITLE
Easier authoring of assessment "directions"

### ISSUE THREAD

**Issue by daviddalpiaz** [PrairieLearn/PrairieLearn#5277] opened 2022-01-18 04:15 UTC
Often, additional information and directions are added to assessments through the use of the `text` field in `infoAssessment.json`. Instead of typing html directly into this field, could this information instead be pulled from an external file?

**Comment by nwalters512** [comment] 2022-01-18 04:20
This is a duplicate of #4028. There's a WIP implementation of this in #4029 - I just need to get it reviewed and deployed 🤞 

I'll close out this issue; feel free to add any additional info or requests to #4028!

**Closed by nwalters512** 2022-01-18 04:20 UTC

**Comment by daviddalpiaz** [comment] 2022-01-18 04:23
Something something "great minds think alike" but I'm not smart enough to search. 🤦
