### ISSUE TITLE
Rendering Externally Graded File Containing Single Space Generates Error

### ISSUE THREAD

**Issue by gchallen** [PrairieLearn/PrairieLearn#1147] opened 2018-05-06 12:07 UTC
![image](https://user-images.githubusercontent.com/445443/39673122-0824b8d4-50fc-11e8-8a51-419756bee199.png)

Note that this is an attempt to work around the fact that an empty externally-graded starter file causes the editor to contain "None" (clearly Python at work) at startup.

**Comment by nicknytko** [comment] 2020-04-08 02:32
@gchallen are you still experiencing this?  I'm not able to reproduce on my end.

**Comment by nicknytko** [comment] 2020-04-16 20:20
Closing, the line in the error seems to have been fixed now and I can't reproduce.

**Closed by nicknytko** 2020-04-16 20:20 UTC
Labels: bug, good first issue
