### ISSUE TITLE
Clean up pl-order-blocks.js to comply to best practices

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4980] opened 2021-10-14 04:21 UTC
the file pl-order-blocks.js doesn't conform well to coding best practices and PrairieLearn conventions and could use some cleanup. 

Specifically: 

- pollutes the global namespace with `TABWIDTH`, `MAX_INDENT`, and with all the functions it uses. It would be better to only add one object to the global namespace and attach all methods and variables defined in the file to that
- using all caps for `MAX_INDENT` even thought it isn't a constant anymore (it used to be)
- uses snake_case instead of camelCase for function names

Feel free to comment anything else we should clean up there

**Comment by SethPoulsen** [comment] 2021-10-14 04:23
see pl-drawing.js for an example of just making one JS object for the element

**Comment by ataraxie** [comment] 2021-10-14 15:50
Sweet issue 🙂 

re global namespace: pl-drawing.js also pollutes the global namespace (`window`). I think this should really only be done if the associated values really need to be accessed from outside the script and can absolutely not be accessed otherwise.

Two options make sense in my opinion:

1. Scripts are wrapped in a self-invoking function (this is what JS processors/transpilers do automatically):

```
(function() {
  // The script
}());
```

2. If `var` will be strictly forbidden by the linter, it should be ok since `let` and `const` don't mess with the global namespace.

I'm expecting that @nwalters512 will have a strong opinion on the matter 😄

**Comment by ataraxie** [comment] 2021-10-14 16:02
I'd be happy to go over it once your other PR (#4981) is merged (I didn't explicitly review it because I'm not a reviewer but it looks good to me). I had already changed most of these things locally anyway; just for fun.

**Comment by nwalters512** [comment] 2021-10-14 17:25
> re global namespace: pl-drawing.js also uses the global namespace (`window`). I think this should really only be done if the associated values really need to be accessed from outside the script and can absolutely not be accessed otherwise.

`<pl-drawing>` has a good reason to put things in the global scope: when the element is rendered, we also render a script tag that's responsible for instantiating the element with its particular config:

https://github.com/PrairieLearn/PrairieLearn/blob/3aa29e946648a09dc310d75d3681de5f3be36697/elements/pl-drawing/pl-drawing.mustache#L54

We do something similar for `<pl-file-editor>` too

https://github.com/PrairieLearn/PrairieLearn/blob/3aa29e946648a09dc310d75d3681de5f3be36697/elements/pl-file-editor/pl-file-editor.mustache#L6

The key thing here is that these scripts (`pl-drawing.js`, etc.) are reused across multiple instances of the same element. This is actually a big issue with `<pl-order-blocks>` in its current state: `MAX_INDENT` is inadvertently shared across all instances of the element on the page, which is definitely not intended behavior. Even putting things in a closure wouldn't fix that,l and that's part of the reason that `pl-drawing` and `pl-file-editor` work the way they do, they allow an easy way to have per-element-instance state.

Long term, the right thing to do is probably to use Web Components for all element code, but we're a ways away from that at the moment.

**Closed** 2021-11-03 20:36 UTC
