### ISSUE TITLE
PL-file-Editor Settings button not woking on deployed instances

### ISSUE THREAD

**Issue by louisunlimited** [PrairieLearn/PrairieLearn#6492] opened 2022-10-17 03:56 UTC
I tried the new settings button on my school's instance. The button is there, but the modal won't pop up. I ran this on my local machine and it seems to be working just fine. Not sure what happened, but I would be happy to fix it if someone could provide some insights.

**Comment by louisunlimited** [comment] 2022-10-17 04:07
Looks like it could be a jquery issue?  I'm not seeing style=" display: none " on the deployed instance as opposed to my local environment. I'm no expert but I believe jquery is handling this style toggling.

Deployed <not working>:
<img width="675" alt="Screen Shot 2022-10-16 at 23 05 29" src="https://user-images.githubusercontent.com/20884681/196087024-8c5a9406-9a6a-4184-92be-41e4838900a2.png">
Local <working>:
<img width="685" alt="Screen Shot 2022-10-16 at 23 05 55" src="https://user-images.githubusercontent.com/20884681/196087075-21a08d45-69c9-4c2f-b5d5-706afee2b838.png">

**Comment by louisunlimited** [comment] 2022-10-17 04:18
Wait, actually the `pl-file-editor.js` file was not being updated at all. I tried to locate`pl-file-editor.js`, and found out it did not include any of the newest commits.
<img width="647" alt="Screen Shot 2022-10-16 at 23 17 09" src="https://user-images.githubusercontent.com/20884681/196088330-c2e995d7-6a4b-4c6a-b272-4969a0046ded.png">

**Comment by nwalters512** [comment] 2022-10-17 04:36
Which course are you taking? I'm guessing it's CS 233 or CS 357, in which case this is an unfortunate byproduct of the way we handle our canary deployments: your page would get rendered by the canaries running the new code, but static assets would be served by the non-canary instances that aren't yet running new code.

cc @mwest1066 we may want to rethink how canaries are done - I can see the root cause here causing any number of confusing issues.

**Comment by louisunlimited** [comment] 2022-10-17 04:45
@nwalters512 Oh, that explains the issue here. It's very interesting to know! Thanks for the explanation!

**Comment by nwalters512** [comment] 2023-05-03 23:58
This specific issue with `pl-file-editor` should no longer exist in prod. We're internally tracking some potential improvements to the way we deploy and serve assets. I'll close this issue in favor of those.

**Closed by nwalters512** 2023-05-03 23:58 UTC
