### ISSUE TITLE
Questions about Exam Submission Status and unanswered questions during manual grading

### ISSUE THREAD

**Issue by kaiqianyyang** [PrairieLearn/PrairieLearn#9367] opened 2024-02-02 08:44 UTC
Hi, I am currently working on writing PL exam, and I realize that for some of the questions, if they are left unanswered, student click finish the assessment and I grade one of answered questions, those questions that are not answered will showing me errors like below. 

<img width="1114" alt="Screenshot 2024-02-02 at 12 37 29 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/3ad328d5-5a92-46ac-8b70-e21c73bd98cd">
<img width="1084" alt="Screenshot 2024-02-02 at 12 37 47 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/24590e0a-849d-47e4-9d5f-51e3d2f83bc3">
<img width="1073" alt="Screenshot 2024-02-02 at 12 37 56 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/59126628-4dd1-475e-9b59-4d0ccf65f933">
Why it happened? How can I solve it?

Within the questions I used:
```
<pl-rich-text-editor
	file-name="tmp.html"
	quill-theme="bubble"
	placeholder="Your answer here"
></pl-rich-text-editor> 
```

It seems that each time I try to test this individual question, it also shows me errors like below, are these issues related? How can I solve it? Any help would really appreciated.

<img width="830" alt="Screenshot 2024-02-02 at 12 41 47 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/31a5db27-683e-4826-b572-b5125bfe20d7">
<img width="831" alt="Screenshot 2024-02-02 at 12 41 58 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/d89e68fc-9be7-425e-8d7a-0a494bdd3d07">

**Comment by nwalters512** [comment] 2024-02-02 18:08
There are two separate issues here:

- "assessment instance is not open"
- Question test failures

For the first one, please provide specific step-by-step instructions to reproduce the error you see.

For the second, please break it out into a discussion (https://github.com/PrairieLearn/PrairieLearn/discussions) as I don't believe this is actually an issue with PrairieLearn.

**Comment by kaiqianyyang** [comment] 2024-02-02 18:24
The first issue:
As an instructor, I created an exam with all manual grading questions, all questions are consisted with below code 
```
<pl-question-panel>
	<p>
		Questions
	</p>
</pl-question-panel>

<pl-rich-text-editor
	file-name="tmp.html"
	quill-theme="bubble"
	placeholder="Your answer here"
></pl-rich-text-editor>

<pl-submission-panel>
  <pl-feedback></pl-feedback>
</pl-submission-panel>
```
and my info.json for each question is exactly like below:
```
{
    "uuid": "***",
    "title": "***",
    "topic": "topic",
    "gradingMethod": "Manual",
    "tags": [
        "mwest",
        "fa17"
    ],
    "singleVariant": true,
    "type": "v3"
}
```
And for the json files under courseInstance/[courseterm], I have 

InfoCourseInstance.json like below:
```
{
    "uuid": "***",
    "shortName": "TC 101",
    "longName": "2023W2",
    "autoClose": true,
    "timezone": "Canada/Pacific",
    "allowAccess": [
        {
            "startDate": "2014-01-19T00:00:01",
            "endDate": "2400-05-13T23:59:59"
        }
    ]
}
```

InfoAssessment.json file like below:
```
{
    "uuid": "****",
    "type": "Exam",
    "title": "Test 1",
    "set": "Q",
    "number": "1",
    "allowRealTimeGrading": false,
    "shuffleQuestions": false,
    "allowAccess": [
        {
            "mode": "Exam",
            "credit": 100
        },
        {
            "mode": "Public",
            "credit": 100,
            "startDate": "2024-02-01T08:00:00",
            "endDate": "2024-02-01T20:04:59",
            "timeLimitMin": 50,
            "showClosedAssessment": false,
            "showClosedAssessmentScore": false
        }
    ],
    "zones": [
        {
            "questions": [
                {
                    "points": 0,
                    "id": [cheat_sheet]
                }
            ]
        },
        {
            "questions": [
                {
                    "id": [question_one_path],
                    "manualPoints": 5
                },
                {
                    "id": [question_two_path],
                    "manualPoints": 15
                }
            ]
        }
    ]
}


```
<hr/>
What I did was:
1. Create test like above
2. In the student view, as a student, I open the test, only answer question1, but not write anything in question2 (leave its submission status 'unanswered'), then just click finish assessment button.
3. In the staff view, I grade question1.
4. In the student without access restriction view, I go to my test, click question 1, I can see the question content and grade, but when I click question 2, it shows me below errors.
<img width="1117" alt="Screenshot 2024-02-02 at 10 23 52 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/88296922/08fbda79-7f67-44cc-bee6-a71c9680b55f">

**Comment by kaiqianyyang** [comment] 2024-02-02 18:40
And what I notice, the question that this error shows up is randomized. Like if I have 6 questions and only answer question 3 then grade it, sometimes question 4 will show this error and all others are fine. But if I do the quiz again, under same scenario, it will show me question 5 with this error page...

**Comment by nwalters512** [comment] 2024-02-02 19:38
> What I did was: 1. Create test like above 2. In the student view, as a student, I open the test, only answer question1, but not write anything in question2 (leave its submission status 'unanswered'), then just click finish assessment button. 3. In the staff view, I grade question1. 4. In the student without access restriction view, I go to my test, click question 1, I can see the question content and grade, but when I click question 2, it shows me below errors.

Did you ever open question 2? Or were your steps exactly this:

- As a student, start the assessment
- As a student, open question 1
- As a student, submit to question 1
- As a student, return to the assessment overview
- As a student, click "Finish assessment"
- As a student, open question 2

**Comment by kaiqianyyang** [comment] 2024-02-02 19:41
> > What I did was: 1. Create test like above 2. In the student view, as a student, I open the test, only answer question1, but not write anything in question2 (leave its submission status 'unanswered'), then just click finish assessment button. 3. In the staff view, I grade question1. 4. In the student without access restriction view, I go to my test, click question 1, I can see the question content and grade, but when I click question 2, it shows me below errors.
> 
> Did you ever open question 2? Or were your steps exactly this:
> 
> * As a student, start the assessment
> * As a student, open question 1
> * As a student, submit to question 1
> * As a student, return to the assessment overview
> * As a student, click "Finish assessment"
> * As a student, open question 2

One things different before the last step,
As a student, click "Finish assessment"
**As a instructor, grade question 1**
As a student, open question 2

**Comment by nwalters512** [comment] 2024-02-02 19:44
Whether or not question 1 is graded isn't relevant here. What you're experiencing is an unfortunate consequence of you or the student never actually viewing the question while the assessment was open. This is described in detail here: https://github.com/PrairieLearn/PrairieLearn/issues/1718

Since this problem is already documented in another issue, I'm going to close this one as a duplicate. You can subscribe to the other issue if you'd like to receive updates on any potential improvements we may implement.

**Closed by nwalters512** 2024-02-02 19:44 UTC
