### ISSUE TITLE
Ambiguous error message to students: Could not parse the grading results.

### ISSUE THREAD

**Issue by celinaberg** [PrairieLearn/PrairieLearn#6605] opened 2022-11-03 19:03 UTC
It turns out students were getting this message (Could not parse the grading results) when they submitted code where a test failed.  This did not appear when all of the tests passed.

This question was related to File I/O and I had 2 tests that used a fairly large file (thousands of lines).  I reduced the size of this input file and the error message went away.  I could not replicate this in my dev environment. 
This is the question: https://ca.prairielearn.com/pl/course_instance/2396/instructor/question/245234/preview

Funny thing is, I am using a much bigger file in this question and I not encountering the same problem.
https://ca.prairielearn.com/pl/course_instance/2396/instructor/question/243128/preview

This question was generating too much output and got the message 'result is too large' and so I fixed this by reducing the output but did not reduce the size of the input file.  

Looking more closely at the difference between these questions, perhaps it is call to copy of a REALLY large list that is causing the problem.

**Comment by nwalters512** [comment] 2022-11-03 19:23
We already have specific handling for the case where the result is too large:

https://github.com/PrairieLearn/PrairieLearn/blob/b1bd7622bee7b2352906bcd0ab00a3218d8b58c3/grader_host/index.js#L546

Given that, I suspect there's something else at play. Can you provide a link to a question where this occurred, or steps to reproduce this locally?

**Comment by celinaberg** [comment] 2022-11-03 19:42
you are right!  I had two different error messages that I was mixing together.  Let me update my initial message.

**Comment by nwalters512** [comment] 2022-11-03 20:47
Could you link to a specific student instance where you see a bug? Alternatively, you could provide the contents we can use for four files to reproduce the issue.

**Comment by celinaberg** [comment] 2022-11-04 01:31
is this what you are looking for:
[https://ca.prairielearn.com/pl/course_instance/2396/instance_question/36445834/](url)
it was his first submission

**Comment by nwalters512** [comment] 2022-11-08 01:38
@celinaberg if you open the `results.json` file from that first submission, you'll see that it contains a control character that's not allowed in JSON. We can certainly add more details to the error message; for instance, trying to open that `results.json` file in Firefox provides a nice error message:

```
SyntaxError: JSON.parse: bad character in string literal at line 37 column 594 of the JSON data
```

We should include essentially that same error message in the user-facing one too. That will at least help you understand the underlying problem, but it won't fix it. I think the root cause is an issue with how we serialize feedback to JSON. cc @nicknytko it looks like the Python grader is in play here; can you think of any reason why feedback containing control characters and added with `Feedback.add_feedback(feedback)` wouldn't be properly escaped?

**Comment by nicknytko** [comment] 2022-11-08 02:33
> @celinaberg if you open the `results.json` file from that first submission, you'll see that it contains a control character that's not allowed in JSON. We can certainly add more details to the error message; for instance, trying to open that `results.json` file in Firefox provides a nice error message:
> 
> ```
> SyntaxError: JSON.parse: bad character in string literal at line 37 column 594 of the JSON data
> ```
> 
> We should include essentially that same error message in the user-facing one too. That will at least help you understand the underlying problem, but it won't fix it. I think the root cause is an issue with how we serialize feedback to JSON. cc @nicknytko it looks like the Python grader is in play here; can you think of any reason why feedback containing control characters and added with `Feedback.add_feedback(feedback)` wouldn't be properly escaped?
> 
> Specifically, It looks like the ASCII character `1A` (https://en.wikipedia.org/wiki/Substitute_character) appears in the resulting JSON. I don't know how it got there; @celinaberg do you think your code or your student's code could be adding that?

I can't say anything for sure without looking at the question details, but I don't *think* there's any reason the Feedback class would be randomly adding weird ascii characters

**Closed** 2022-11-08 17:25 UTC
