### ISSUE TITLE
Student should not be able to be included in more than one group assessement

### ISSUE THREAD

**Issue by mfsilva22** [PrairieLearn/PrairieLearn#3379] opened 2020-10-28 14:37 UTC
I noticed that in a group assessment using Homework mode and the join/create/leave features turned on, one student was able to assign themself to the same group twice. Here is what they see (and reported)

![image](https://user-images.githubusercontent.com/12501485/97450623-eeade400-1900-11eb-97c0-5da95de8600a.png)

I was able to confirm this going to the student page. Indeed, if I check the created group, it has the student netid showing twice.

This looks like a bug, since students should only be able to be added to one group for each given assessment.

**Comment by jonatanschroeder** [comment] 2024-07-30 16:35
Duplicate of #8394. This one is older, but that one has a longer discussion, so closing this one.

**Closed by jonatanschroeder** 2024-07-30 16:35 UTC
Labels: bug
