### ISSUE TITLE
Matrices may render incorrectly when zoomed in

### ISSUE THREAD

**Issue by devksingh4** [PrairieLearn/PrairieLearn#6756] opened 2022-12-08 18:01 UTC
When the window is zoomed in, PL may not render augmented matrices correctly and gets rid of the augment bar. For example:

![image](https://user-images.githubusercontent.com/18728114/206529443-1c83af3f-9648-4abb-946e-30495a244ab4.png)

I assume this has to do with the responsive CSS seeing the augment bar as not part of the matrix.

**Comment by nwalters512** [comment] 2022-12-08 18:05
We use [MathJax](https://github.com/mathjax/MathJax) to render all math, so this almost certainly isn't an issue with PrairieLearn itself. If you can provide the LaTeX source that's being rendered, I can try to reproduce in isolation and report it upstream to the MathJax maintainers. In the meantime, it'd be helpful to know which OS and browser you're using.

**Comment by devksingh4** [comment] 2022-12-08 18:08
LaTeX source:
```latex
\left[
                \begin{matrix}
                    2 & 3 \\
                    2 & 7 \\
                    0 & -4
                \end{matrix}
                \;\middle|\;
                \begin{matrix}
                    2 \\
                    -1 \\
                    3
                \end{matrix}
            \right].
 ```
 
 I'm running Chrome 108.0.5359.96 on Windows 11 22H2.

**Comment by devksingh4** [comment] 2022-12-08 18:10
Just to add: I was zoomed in about 400% (trying to hide the answers), so it is a bit of an edge case.

**Comment by nwalters512** [comment] 2022-12-08 18:24
That is definitely quite the edge case! Since this is highly unlikely to affect normal usage, I won't personally go through the trouble of filing an issue with MathJax. If you'd like to see this fixed, I'd encourage you to do so yourself. I'll go ahead and close this issue; if/when this is fixed upstream, we'll eventually pick up the fix via an automated dependency bump.

**Closed by nwalters512** 2022-12-08 18:24 UTC

**Comment by echuber2** [comment] 2022-12-08 21:42
I think the issue must be related to this:

**Comment by echuber2** [comment] 2022-12-08 21:44
I think the issue must be related to this: https://github.com/PrairieLearn/PrairieLearn/pull/3520

But I thought that avoiding SVG on Windows+Chrome (as we do) was solving that issue.
