### ISSUE TITLE
Slow page loads on Manual Grading Page

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#9099] opened 2023-12-21 21:55 UTC
Paul C. reported that this page is extremely slow to load:

<img width="573" alt="Screenshot 2023-12-21 at 1 54 23 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/d6c349f0-6d92-4f99-8ecd-1ab9809d7140">

Link to page that's slow: https://ca.prairielearn.com/pl/course_instance/4288/instructor/assessment/39810/manual_grading/assessment_question/56714956

On first load, it takes me roughly 30 seconds for the page to load, but subsequent refreshes of the same page is pretty fast (3-5 seconds).

There are ~600 instances on this page.

As discussed in PL office hours today, I'm just reporting the issue here.

**Comment by mwest1066** [comment] 2023-12-21 22:18
@jonatanschroeder from the description it looks like this is a slow query which is then fast when everything is cached. Let me know if you want me to pull data (or an EXPLAIN ANALYZE) from prod.

**Comment by jonatanschroeder** [comment] 2023-12-22 01:35
Analyze would be useful. I'm wondering if the delay is in the call to `groups_uid_list` in: https://github.com/PrairieLearn/PrairieLearn/blob/84b990af6d9ec5254da59eab7f5eb1b7b72d2ae1/apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.sql#L37

or maybe if the issue count is doing something weird like using the `instance_question_id` index instead of the `assessment_id` index... All queries seem to have reasonable indexes to back them up.

**Comment by mwest1066** [comment] 2023-12-22 16:17
Here's the EXPLAIN ANALYZE for this query: https://github.com/PrairieLearn/PrairieLearn/blob/1cb19129065b3c38fd1d986e8fb0da16df3c68e4/apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.sql#L1 with parameters `assessment_id: 39810` and `assessment_question_id: 56714956`.

I don't see anything suspicious here and everything looks fast. The exact output below is from a query with hot caches but the cold-cache output looked similar (somewhat higher execution time, but still fast).

```
                                                                                                                         QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=2924.92..2924.93 rows=1 width=582) (actual time=68.689..68.742 rows=584 loops=1)
   Sort Key: (COALESCE(g.name, u.name)), iq.id
   Sort Method: quicksort  Memory: 351kB
   ->  Nested Loop Left Join  (cost=1228.92..2924.91 rows=1 width=582) (actual time=1.642..66.937 rows=584 loops=1)
         Join Filter: (i.instance_question_id = iq.id)
         Rows Removed by Join Filter: 4653
         ->  Nested Loop Left Join  (cost=1220.47..2916.41 rows=1 width=540) (actual time=1.585..63.230 rows=584 loops=1)
               ->  Nested Loop Left Join  (cost=1220.18..2912.24 rows=1 width=511) (actual time=1.577..61.439 rows=584 loops=1)
                     ->  Nested Loop Left Join  (cost=1219.89..2908.07 rows=1 width=482) (actual time=1.562..58.340 rows=584 loops=1)
                           ->  Nested Loop Left Join  (cost=1219.64..2907.80 rows=1 width=458) (actual time=1.385..9.737 rows=584 loops=1)
                                 ->  Nested Loop Left Join  (cost=1219.35..2903.60 rows=1 width=451) (actual time=1.378..8.887 rows=584 loops=1)
                                       ->  Nested Loop  (cost=1219.06..2901.40 rows=1 width=430) (actual time=1.365..6.534 rows=584 loops=1)
                                             ->  Hash Join  (cost=1218.65..2892.96 rows=1 width=406) (actual time=1.344..3.413 rows=584 loops=1)
                                                   Hash Cond: (ai.id = iq.assessment_instance_id)
                                                   ->  Index Scan using assessment_instances_assessment_id_user_id_number_key on assessment_instances ai  (cost=0.43..1672.58 rows=824 width=25) (actual time=0.032..1.194 rows=589 loops=1)
                                                         Index Cond: (assessment_id = 39810)
                                                   ->  Hash  (cost=1214.87..1214.87 rows=268 width=389) (actual time=1.303..1.304 rows=584 loops=1)
                                                         Buckets: 1024  Batches: 1  Memory Usage: 266kB
                                                         ->  Index Scan using instance_questions_assessment_question_id_assessment_instan_key on instance_questions iq  (cost=0.56..1214.87 rows=268 width=389) (actual time=0.023..0.908 rows=584 loops=1)
                                                               Index Cond: (assessment_question_id = 56714956)
                                                               Filter: (status <> 'unanswered'::enum_instance_question_status)
                                                               Rows Removed by Filter: 5
                                             ->  Index Scan using assessment_questions_pkey on assessment_questions aq  (cost=0.41..8.43 rows=1 width=32) (actual time=0.004..0.004 rows=1 loops=584)
                                                   Index Cond: (id = 56714956)
                                       ->  Index Scan using users_pkey on users u  (cost=0.29..2.20 rows=1 width=37) (actual time=0.003..0.003 rows=1 loops=584)
                                             Index Cond: (user_id = ai.user_id)
                                 ->  Index Scan using groups_pkey on groups g  (cost=0.29..4.20 rows=1 width=15) (actual time=0.000..0.000 rows=0 loops=584)
                                       Index Cond: (id = ai.group_id)
                           ->  Function Scan on groups_uid_list gul  (cost=0.25..0.26 rows=1 width=32) (actual time=0.082..0.082 rows=1 loops=584)
                     ->  Index Scan using users_pkey on users agu  (cost=0.29..4.17 rows=1 width=37) (actual time=0.003..0.003 rows=1 loops=584)
                           Index Cond: (user_id = iq.assigned_grader)
               ->  Index Scan using users_pkey on users lgu  (cost=0.29..4.17 rows=1 width=37) (actual time=0.002..0.002 rows=1 loops=584)
                     Index Cond: (user_id = iq.last_grader)
         ->  GroupAggregate  (cost=8.45..8.47 rows=1 width=16) (actual time=0.001..0.004 rows=8 loops=584)
               Group Key: i.instance_question_id
               ->  Sort  (cost=8.45..8.46 rows=1 width=8) (actual time=0.000..0.001 rows=8 loops=584)
                     Sort Key: i.instance_question_id
                     Sort Method: quicksort  Memory: 25kB
                     ->  Index Scan using issues_assessment_id_open_idx on issues i  (cost=0.42..8.44 rows=1 width=8) (actual time=0.031..0.038 rows=8 loops=1)
                           Index Cond: ((assessment_id = 39810) AND (course_caused = true) AND (open = true))
 Planning Time: 1.782 ms
 Execution Time: 68.977 ms
(42 rows)
```

**Comment by mwest1066** [comment] 2023-12-22 16:26
I also ran EXPLAIN ANALYZE for some pages on the US server that I think had cold caches and which had similar numbers of rows (600ish). The query plan was similar, with execution times around 400 ms that then dropped to 80 ms with warm caches.

**Comment by jonatanschroeder** [comment] 2023-12-22 17:28
Could this delay be something other than queries? Either server side (parsing and JSON formatting), client side (bootstrap table) or networking?

**Comment by nwalters512** [comment] 2024-01-03 19:33
@firasm are you still able to reproduce this? The entire page loads in under 1 second for me.

**Comment by firasm** [comment] 2024-01-04 08:22
No, cannot reproduce anymore - it's pretty speedy now!

I showed @mwest1066 in office hours and I thought he was able to reproduce it also. At the time I reported it, it took half a minute to load. But I agree this is now very fast.

**Comment by nwalters512** [comment] 2024-01-04 23:12
Weird! I'm going to close this for now, but if at some point in the future you're able to consistently reproduce this again, please comment here and I'll reopen this for further investigation.

**Comment by firasm** [comment] 2024-01-23 01:47
Hi all,

It seems my TAs are also experiencing issues loading the [Manual Grading page](https://us.prairielearn.com/pl/course_instance/147046/instructor/assessment/2387106/manual_grading/assessment_question/673789540): 

<img width="774" alt="Screenshot 2024-01-22 at 5 41 57 PM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/6a49ba21-0323-41a3-ac44-6db60eab9c7c">

Could we re-open this?

**Comment by nwalters512** [comment] 2024-01-23 02:43
@firasm I can't reproduce any performance issues with that linked page; it reliably loads completely in roughly 1 second for me. I also checked our raw load balancer logs and wasn't able to find a single individual request (either for this page or for the JSON data it loads) that took more than 250ms. I'm inclined to call this an issue with their network or device.

If your TAs still feel there is a performance issue for us to look into, you can direct them to this issue to share specific network/timing information. For instance, here's the network traffic I captured in the Chrome dev tools "Network" tab from a page load just now:

<img width="1353" alt="Screenshot 2024-01-22 at 18 32 28" src="https://github.com/PrairieLearn/PrairieLearn/assets/1476544/2b9a723c-9862-4d81-b650-922abc17056e">

Without either further information or a way for us to independently reproduce the perceived slowness, I won't reopen this issue as there's no concrete information for us to go off.

The second message that mentions "the PL search function was horribly slow" feels like a different problem. Your TA can open a separate issue with a more complete set of information if they feel there's a performance issue with "the PL search function" (I don't know what that's referencing).

**Comment by mwest1066** [comment] 2024-01-23 15:55
I could reliably reproduce the issue with the original page, but only on queries that weren't cached by postgres. Once postgres has paged in the data everything was super fast.

**Comment by mwest1066** [comment] 2024-01-23 16:34
Apologies to everyone, I mistakenly thought this was a different issue. I agree with @nwalters512 that all our data at the moment suggests that this is a problem on the client side, so I'll close this issue again.

I also don't know what "the PL search function" refers to here. Maybe they are referring to the search box on the "Students" page? That's super fast in my testing so I'm inclined to put this down to client-side problems again that we'd need more data from the TAs to investigate.

**Closed by mwest1066** 2024-01-23 16:34 UTC
Labels: bug, feature: manual grading

**Comment by firasm** [comment] 2024-01-23 16:59
Thanks for trying this Nathan, we have a TA meeting today with about 20 of them, hopefully we have some time left so I will get them to clear their cache and try to all reproduce at the same time.

I just recorded a video where I first visited the page on Chrome (it was fine) and then when I went to it subsequently in Safari, it took about 12 s to load. 

I have a longer screen recording I'll share privately (because it has student info), but in the meantime, see the anonymized snippet with the timer running:

![PL_perceived_slowness](https://github.com/PrairieLearn/PrairieLearn/assets/2507459/cee26446-13af-4c90-bfe3-0a790e0b846e)

Here are some timing data for **a different page load** (sorry about the piecemeal info - have to run to teach soon but will try to collect all relevant data in one place).

<img width="1727" alt="Screenshot 2024-01-23 at 8 57 19 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/19743cf5-5bbe-482f-bbcc-90b800c6b75b">


<img width="1727" alt="Screenshot 2024-01-23 at 8 57 05 AM" src="https://github.com/PrairieLearn/PrairieLearn/assets/2507459/26dd5260-7a34-4b3c-9099-a7fb6b08aa94">

**Comment by nwalters512** [comment] 2024-01-23 17:18
> I just recorded a video where I first visited the page on Chrome (it was fine) and then when I went to it subsequently in Safari, it took about 12 s to load.

Is it fair to say that you only experience performance issues in Safari? This seems to be a useful observation, as I'm also able to reproduce somewhat reduced performance in Safari (though it still doesn't take 12 seconds for me). Firefox is as performant as Chrome is for me.

The fact that your CPU usage is pinned to ~100% for 16 seconds is deeply suspicious. Can you dig into that for me? Is there a possibility that you have one or more misbehaving extensions? Are you able to reproduce the performance issue in a Private Browsing window with all extensions disabled?

**Comment by firasm** [comment] 2024-01-24 00:36
Quick update after our TA meeting, we tried it live with everyone and there were ~19 TAs present. 

10 reported "yes, they were seeing slowness on the loading of the manual grading page, and searching for UIDs on the same page"

3 of them reported no issues and around 7-8 of them didn't reply.

```
From AZ to Everyone:
	yes - Chrome
	I'm having issues. It takes ~20 seconds to search a UID on the Manual Grading page
From KT to Everyone:
	yes - Chrome
From QS to Everyone:
	yes - Chrome on Windows
From BZ to Everyone:
	yes - Chrome
From SV to Everyone:
	yes - Chrome
From BL to Everyone:
	Yes - Chromium-based browser
From MN to Everyone:
	yes - Safari
From JT to Everyone:
	yes - Firefox
	I don't think it's a new issue either, I remember a lot of people were talking about slow loading during the finals manual grading for 2023W1
From K to Everyone:
	Yes - Firefox
```

I'll keep trying to narrow down the issue on my side, will try no extensions, private browsing, other browsers, etc...

**Comment by nwalters512** [comment] 2024-01-24 00:52
> yes, they were seeing slowness on the loading of the manual grading page, and searching for UIDs on the same page

Just so I make sure we're on the same page: when you talk about "searching for UIDs", do you mean you click "Columns", enable the UID column, then type part of a UID into the search box at the top of the column? If that's indeed what you're referring to, I'm unable to reproduce any slowness here in Chrome, Firefox, _or_ Safari.

Thank you for gathering more information, I'll sit tight until I hear more from you. If we don't get anywhere with this async back-and-forth by Thursday, do you think you and 1-2 of your TAs would be able to join office hours so we can dig into this together?
