### ISSUE TITLE
API Endpoint for Problem Submission

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#1488] opened 2019-04-21 15:21 UTC
STAT has interest in creating a CLI command to submit problem questions to PL to grade via an API. The idea here is we would package and send a file for a specific problem. For instance, we'd have a function within _R_ that collects the students work and sends the file.

Sample command:

```r
submit_pl_ag(file, question_id, course, key)
```

The PL Endpoint would then be:

```
PUT /v1/grade/question/:id/:key/:course
```

This would retrieve the file and, then, launch an _AG_ job. Students would have an API limit of 4 per hour to avoid spamming the API. Some level of caching would be required to prevent regrading a question if mistakenly submitted.

Net benefit, this has the potential to replace the current workflow adopted in CS, which was to add to the `makefile` a zip option created by @echuber2.

**Comment by nwalters512** [comment] 2019-04-21 15:46
I've got a half-finished branch somewhere that does basically this. AFK right now but I'll see if I can find it later.

**Comment by mwest1066** [comment] 2019-07-07 16:53
Definitely a recurring request. @nwalters512: bump for you to dig up your half-written branch.

**Comment by coatless** [comment] 2020-04-21 18:43
Branch that has some of the work need for re-enabling a terminal API file upload...

https://github.com/PrairieLearn/PrairieLearn/tree/question-file-api

**Comment by nwalters512** [comment] 2022-11-02 23:44
Closing as a duplicate of #6525, which has much more robust discussion around this idea. @coatless feel free to chime in on that other issue with any specific thoughts you have!

**Closed by nwalters512** 2022-11-02 23:44 UTC
Labels: enhancement
