### ISSUE TITLE
pl-checkbox doesn't respect max-correct or max-incorrect (in some? cases)

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10067] opened 2024-06-23 15:56 UTC
According to the [docs](https://prairielearn.readthedocs.io/en/latest/elements/#pl-checkbox-element),

`max-correct`: The maximum number of correct answers to display. Defaults to displaying all correct answers.
`min-correct`: The minimum number of correct answers to display. Defaults to displaying all correct answers.

This was my question setup:

```
<pl-checkbox answers-name="select" max-correct="3" partial-credit=true partial-credit-method="EDC">
```

But I was not able to limit the correct options to 3 just by setting `max-correct` to "3". I also had to set number-answers = "6" for the `max-correct` field to take (otherwise it showed more than 3 correct answers).

FWIW, I have 6 answers labeled as correct, and 4 answers labelled as incorrect.

**Comment by eliotwrobson** [comment] 2024-06-23 17:08
I think this is a duplicate of https://github.com/PrairieLearn/PrairieLearn/issues/4430

**Closed** 2024-06-23 22:49 UTC
