### ISSUE TITLE
Enable hiding of Correct Answer panel

### ISSUE THREAD

**Issue by dowobeha** [PrairieLearn/PrairieLearn#2161] opened 2020-03-17 17:17 UTC
There are times where it doesn't make sense to show an answer panel. It would be nice to allow questions to be configured such that this is hidden.

**Comment by echuber2** [comment] 2020-03-17 17:28
I think this is a duplicate of https://github.com/PrairieLearn/PrairieLearn/issues/623

**Comment by nicknytko** [comment] 2020-03-31 21:51
This looks like a duplicate, closing in favour of #623.

**Closed by nicknytko** 2020-03-31 21:51 UTC
