### ISSUE TITLE
Default focus on manual grading

### ISSUE THREAD

**Issue by alifa98** [PrairieLearn/PrairieLearn#6661] opened 2022-11-27 23:04 UTC
Hello all community members,

I had a suggestion for enhancing UX.

The annoying thing is that every time I type a grade and submit by enter button, in the next question I should click this input box to focus again.

![image](https://user-images.githubusercontent.com/31096694/204164090-4c90047e-2bcb-45bc-89db-8e125cf4f4ec.png)

It would be great if we had a keyboard shortcut for focusing on "grade" input or it would be focused by default.
Also, we can use "tabIndex" to reach the input by pressing TAB. (currently, it needs over 20 TAB to reach that input 😄 )

I think this will help graders to grade without using their mouse, simply reading and entering the grade. 😅 

Thank you.

**Comment by nwalters512** [comment] 2022-11-27 23:23
Thanks for the suggestion! This is a duplicate of #6542, I'll close it in favor of that issue. Feel free to add any additional thoughts to that other one.

**Closed by nwalters512** 2022-11-27 23:23 UTC
