### ISSUE TITLE
Validate MC questions with duplicate answers

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#1437] opened 2019-02-26 20:06 UTC
Can we be smarter about trying to weed out multiple-choice questions with duplicate answers? Perhaps on import, or question testing? This tends to be a common occurrence with novice PL content creators and raises questions in the CBTF.

**Comment by nwalters512** [comment] 2019-02-26 20:08
Duplicate of #1228

**Closed by nwalters512** 2019-02-26 20:08 UTC
