### ISSUE TITLE
Better error message when student clicks on never-opened question on closed exam

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#6534] opened 2022-10-25 23:58 UTC
If a student clicks on a question on a closed exam (e.g. to review), but they never opened that question when the exam was open, they get an error message:  "assessment instance is not open"

Students don't know or care that a question variant is generated on demand when they open it (and only if the assessment is open). So it's not obvious to them that there should be an error on this action, and they don't understand the error message. A better error message might help.

**Comment by trombonekenny** [comment] 2022-10-26 00:27
Dupe of #1718

**Comment by nwalters512** [comment] 2022-10-26 00:35
Closing in favor of #1718.

**Closed by nwalters512** 2022-10-26 00:35 UTC
Labels: enhancement, duplicate
