### ISSUE TITLE
Indicate graded students out of total in the manual grading view

### ISSUE THREAD

**Issue by joelostblom** [PrairieLearn/PrairieLearn#10851] opened 2024-10-23 17:21 UTC
When doing manual grading, it can be helpful to see how many students are graded and the total number of students. For myself, I usually grade ~10 students as an example for TAs so it would be convenient to see something like `8/92` (`<graded>/<total>`) instead of navigating back to the question page or keep track of how many time I have clicked submit. I think this could also motivating for TAs to know how many there are left to grade and to split up their graded in chunks.

I think there is space to fit this into the grading box, maybe even right-aligned in the cyan card header that says "grading" (but really anywhere easily visible without scrolling is fine):

![Image](https://github.com/user-attachments/assets/ba8543c7-dc0f-4c13-8a6a-4b0fb236af7c)

**Comment by jonatanschroeder** [comment] 2024-10-23 18:06
Duplicate of #7553.

**Comment by nwalters512** [comment] 2024-10-23 18:33
Closing as a duplicate as Jonatan called out above. @joelostblom if there's any context you feel is missing from that other issue, please feel free to add it there!

**Closed by nwalters512** 2024-10-23 18:33 UTC

**Comment by joelostblom** [comment] 2024-10-23 20:20
Ah sorry, I missed that issue when searching. Thanks for linking it! I'll move over my text as a comment there.
