### ISSUE TITLE
Improve Local Development Experience Using Mise

### ISSUE THREAD

**Issue by reteps** [PrairieLearn/PrairieLearn#11010] opened 2024-12-11 01:53 UTC
I had a slightly annoying time setting up local development due to inconsistent preinstalled versions of things I had (wrong node, wrong postgres, missing pg_vector, missing redis). I have been following along and comparing tools like `pyenv`, `asdf`, etc. for my own local setup. Now there is a tool, `mise`, which I think shows the most promise out of all of them: https://mise.jdx.dev/

It core features stood out to me as adding value:

- makefile replacement with tab completion syntax, and support for CLI flags (https://mise.jdx.dev/tasks/toml-tasks.html#toml-based-tasks, https://mise.jdx.dev/tasks/file-tasks.html#arguments)
- very straightforward dependency lists (https://mise.jdx.dev/dev-tools/#dev-tools)

I might play around with this a little bit and see if one could use mise to get the repo running locally without Docker, and without installing anything extra. Curious if this is something we are interested in: would massively simplify the local development experience, and if we switch the makefiles, running stuff as well.

**Comment by nwalters512** [comment] 2024-12-11 19:37
Closing as a duplicate of #11009.

**Closed by nwalters512** 2024-12-11 19:37 UTC
Labels: RFC
