### ISSUE TITLE
Student's add course button not working

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#580] opened 2017-02-10 18:59 UTC
From Chris Schmitz:

I have a student who can't add ECE110 as a course. Someone shared a "direct link" to homework 3 to allow him to access it. He can see it in the list, but it refuses to be added. He shared this video (I hope it is public): https://drive.google.com/file/d/0ByucyOjm8r2QVTg1cENMdDRsWVE/view

Student was using arch linux and firefox. The student confirmed he could add the course from a windows machine.

Dave couldn't reproduce the problem in docker dev or production from his CentOS firefox.

**Comment by trombonekenny** [comment] 2017-02-10 23:59
@jakebailey can help test.

**Comment by jakebailey** [comment] 2017-02-11 03:52
Worked for me on my Arch laptop, with `firefox 51.0.1-1`. I clicked the ESPL add course button it worked.

**Comment by mwest1066** [comment] 2017-02-13 02:50
I'm closing this due to lack of reproducibility.

**Closed by mwest1066** 2017-02-13 02:50 UTC
Labels: bug

**Comment by echuber2** [comment] 2019-06-13 22:35
Video link is dead, but I wonder if this is related to the issue with popovers. (See https://github.com/PrairieLearn/PrairieLearn/pull/1499 )
