### ISSUE TITLE
Reset a single variant question for a student

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5480] opened 2022-03-02 19:49 UTC
For a single variant question, there is no way to reset the question for a student (short of deleting the entire assessment instance) so that the student gets a "fresh" copy of the question.

Reasons you might need to reset the question -

* you realize the question is broken, you fix it, and you want to give the fixed version to a few students who have already opened the question
* a PL developer changed an element after a student opened a question but before they finished it, and as a result it is broken (I've seen a few cases of this on Slack)
* a TA told me that a student requested the ability to do this for themself (though, if students could "reset" a question by themself, I would them to get the same variant the next time). the TA said:

> On my office hour a student complained that once they answer a homework question correctly they cannot really clear their answers to try it again after some time

**Comment by jonatanschroeder** [comment] 2022-03-03 19:07
#3552 takes care of this issue, not sure how close it is to a final version, though.

**Comment by ffund** [comment] 2022-03-10 19:52
For some idea of impact. A week ago, I first saw an error due to the `pl-order-blocks` implementation changing while an assessment was open. 

In the week since then, it's happened 43 more times just in my class.

**Comment by eliotwrobson** [comment] 2023-06-06 13:43
Looks like this feature is discussed in these PRs:
- https://github.com/PrairieLearn/PrairieLearn/pull/3552
- https://github.com/PrairieLearn/PrairieLearn/pull/3216

Per some discussion with @SethPoulsen, going to put this under the umbrella of question sharing since it interacts very closely with those features.

**Comment by nwalters512** [comment] 2023-06-06 15:20
It is not at all clear to me how this relates to question sharing, could you share the key points of the discussion with Seth here?

**Comment by eliotwrobson** [comment] 2023-06-06 16:10
> It is not at all clear to me how this relates to question sharing, could you share the key points of the discussion with Seth here?

Whoops, meant to leave that comment under this issue: https://github.com/PrairieLearn/PrairieLearn/issues/1041

I actually think this is a duplicate of that issue. Anyway, the reason is similar to the question parameters, just tagging issues / PRs that have something to do with instructor controls for questions.

**Comment by nwalters512** [comment] 2023-06-07 01:34
Resetting *all* open variants is a bit different from resetting a single one, which is what this issue captures, so I don't think we should consider this a duplicate of the other issue.

**Comment by jonatanschroeder** [comment] 2023-12-02 17:50
@nwalters512 should this be tagged to be resolved by #8889?

**Comment by nwalters512** [comment] 2023-12-02 19:42
@jonatanschroeder done!

**Closed** 2024-01-23 23:05 UTC
