### ISSUE TITLE
Jupyter workspace metrics 403 error

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#8629] opened 2023-10-06 14:56 UTC
I loaded up the `demo/workspace/jupyterlab` question in the example course and peeked at the console. Every few seconds it throws a 

`serverconnection.js:205     GET https://us.prairielearn.com/pl/workspace/1236090/container/metrics?1696604061202 403 (Forbidden)`

error. This happens every few seconds.

![image](https://github.com/PrairieLearn/PrairieLearn/assets/10765199/522ed912-06a4-4578-8ba7-0e1390e65af4)

That seems like something we should either disable in the notebook as well (if we can), or make work somehow with workspaces.

**Comment by nwalters512** [comment] 2023-10-06 14:58
Duplicate of #3875.

**Closed by nwalters512** 2023-10-06 14:58 UTC
