### ISSUE TITLE
Add a way for students to see their previous submissions in Homework-type assessments

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#3158] opened 2020-09-21 17:12 UTC
Please add a way for students to see their own history of submissions in Homework-type assessments. This is particularly relevant in file-editor and file-upload style questions (like code).

**Comment by mwest1066** [comment] 2020-09-21 20:30
For questions like the ones you reference, you might want to set `"singleVariant": true` in the question `info.json`. This will show all previous submissions.

On the question page, PL shows all the submissions for the current question variant (the particular random instance of the question). On exams there is only one variant per question, which is why exams show all previous submissions. Homeworks normally generate new variants for every attempt, which is why they don't show previous submissions. A homework question that has `"singleVariant": true` will behave like an example question in so far as submission-display is concerned.

**Comment by jonatanschroeder** [comment] 2020-09-21 20:55
Thanks, that solves most common issues, but we still have coding questions with multiple variants that we want to keep, and give students a chance to practice with those variants.

**Comment by mwest1066** [comment] 2020-09-21 21:00
Yep, understood. This is just a work-around until we can address all the cases properly.

I think this issue is actually a duplicate of #29 (ancient issue!) 😄 -- I'm going to leave this one open as well because it has valuable additional context.

**Closed** 2024-04-28 21:20 UTC
Labels: enhancement, diff:medium
