### ISSUE TITLE
Show invalid answer feedback on question panel too

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#4246] opened 2021-05-23 22:39 UTC
Currently feedback for invalid answers is shown only on the submitted panel, not on the question panel. Correct/incorrect answer feedback, though (e.g., green checkbox, red X), is shown on both submitted panel and question panel. It may be good for consistency to also show the invalid answers feedback ("invalid" text plus the "Why" button) to also show on the question panel after submission. This can be useful particularly for longer questions, so students can see the feedback in the same panel that allows them to update the answer.

This is a problem at least in `pl-integer-input` and `pl-symbolic-input`. I haven't tried other types of input, but other types of input that could cause invalid values should probably be considered as well.

**Comment by eliotwrobson** [comment] 2023-06-03 14:31
Closing as a duplicate of #5902. However, this change is currently in PR for the integer element, and is planned for all elements!

**Closed** 2023-06-03 14:32 UTC

**Comment by cbm755** [comment] 2023-06-03 20:35
> and is planned for all elements!

Why closed as "not planned" then?

**Comment by nwalters512** [comment] 2023-06-03 20:38
GitHub gives exactly two options to close issues:

![IMG_1004](https://github.com/PrairieLearn/PrairieLearn/assets/1476544/5923f50a-1264-44c4-8280-4e24103cf0e4)
